### ISSUE TITLE
[Feature]: Keeping "Team" after the "About Us" section

### ISSUE THREAD

**Issue by PurneswarPrasad** [commclassroom/commclassroom#241] opened 2021-10-03 09:46 UTC
### Is your feature request related to a problem? Please describe.

Whenever one comes to a certain website, they'd like to see about the content and then the team, contact details, etc. And also, in the navigation tabs, keeping "Team" before "About Us" makes it navigate down first and then it comes up for the "About Us".

### Describe the solution you'd like

Swapping the position of "Team" and "About Us" navigation buttons on the Landing page

**Comment by PurneswarPrasad** [comment] 2021-10-03 09:47
@kaiwalyakoparkar @kunal-kushwaha this can be a `good-first-issue`. Review and add the tag.

**Comment by mayankjain25** [comment] 2021-10-03 10:21
Can I be assigned this task?

**Comment by UjjwalSinghDetexter** [comment] 2021-10-05 07:10
i Have submitted its pull request

**Comment by PurneswarPrasad** [comment] 2021-10-05 10:57
@UjjwalSinghDetexter do link the issue with your PR for better visibility

**Comment by UjjwalSinghDetexter** [comment] 2021-10-05 15:45
@PurneswarPrasad Done, it it ok now?

**Comment by UjjwalSinghDetexter** [comment] 2021-10-05 15:51
@PurneswarPrasad Done, is it good now?

**Comment by kaiwalyakoparkar** [comment] 2021-10-06 04:58
@UjjwalSinghDetexter Please don't raise a PR if the issue is not assigned. It's not a good practice.

**Comment by UjjwalSinghDetexter** [comment] 2021-10-06 05:23
@kaiwalyakoparkar Sorry, i will not do that again

**Comment by UjjwalSinghDetexter** [comment] 2021-10-06 05:26
@kaiwalyakoparkar you have assigned this issue to me, so should i raise a new pr or the one i did before is fine?

**Comment by UjjwalSinghDetexter** [comment] 2021-10-15 18:27
@kaiwalyakoparkar i have mentioned issue in my pr please have a look.

**Closed** 2021-11-17 16:20 UTC
Labels: good first issue
