### ISSUE TITLE
[docs]Adding a README for the repository

### ISSUE THREAD

**Issue by prnvtripathi** [commclassroom/commclassroom#128] opened 2022-11-15 04:02 UTC
### Category of documentation update

Updating the current README.md file.

**Comment by AnuragThePathak** [comment] 2022-11-17 17:00
Closing as duplicate of https://github.com/commclassroom/commclassroom/issues/50

**Closed by AnuragThePathak** 2022-11-17 17:00 UTC
Labels: documentation

**Comment by prnvtripathi** [comment] 2022-11-18 02:22
Hey, @AnuragThePathak there is not a good readme file there
